import {
  Accessibility,
  Balloon,
  Banknote,
  Bike,
  Blocks,
  BookMarked,
  BowArrow,
  Building,
  Bus,
  Cable,
  CarTaxiFront,
  Cat,
  Cctv,
  Church,
  CookingPot,
  Cross,
  Dog,
  Drama,
  Droplet,
  Droplets,
  FireExtinguisher,
  Footprints,
  Fuel,
  Gavel,
  GraduationCap,
  HeartPulse,
  Hospital,
  Hotel,
  House,
  HouseHeart,
  Landmark,
  Map,
  Microscope,
  PersonStanding,
  Rabbit,
  Recycle,
  Road,
  Rose,
  Rows4,
  School,
  Shield,
  Siren,
  Sprout,
  SquareParking,
  Store,
  Toilet,
  TrainFront,
  TramFront,
  Trash2,
  TreePalm,
  TreePine,
  Volleyball,
  Wallet,
  Wifi,
  Wind,
  Zap,
} from "lucide-react-native";

export const CATEGORIES = [
  {
    id: "education",
    label: "Obrazovanje, kultura i sport",
    description: "Velit cursus magna fringilla natoque.",
    icon: GraduationCap,
    dataSets: [
      {
        label: "Studentski restoran",
        description: "Velit cursus magna fringilla natoque.",
        icon: CookingPot,
      },
      {
        label: "Studentsko naselje",
        description: "Velit cursus magna fringilla natoque.",
        icon: Hotel,
      },
      {
        label: "Kulturne ustanove",
        description: "Velit cursus magna fringilla natoque.",
        icon: Landmark,
      },
      {
        label: "Osnovne škole",
        description: "Velit cursus magna fringilla natoque.",
        icon: School,
      },
      {
        label: "Odmorko",
        description: "Velit cursus magna fringilla natoque.",
        icon: TreePalm,
      },
      {
        label: "Kultura",
        description: "Velit cursus magna fringilla natoque.",
        icon: Drama,
      },
      {
        label: "Javna sportska igrališta",
        description: "Velit cursus magna fringilla natoque.",
        icon: Volleyball,
      },
      {
        label: "Visokoškolske ustanove",
        description: "Velit cursus magna fringilla natoque.",
        icon: GraduationCap,
      },
      {
        label: "Sportski objekti",
        description: "Velit cursus magna fringilla natoque.",
        icon: Volleyball,
      },
      {
        label: "Učenički domovi",
        description: "Velit cursus magna fringilla natoque.",
        icon: Building,
      },
      {
        label: "Srednje škole",
        description: "Velit cursus magna fringilla natoque.",
        icon: School,
      },
      {
        label: "Studentska naselja",
        description: "Velit cursus magna fringilla natoque.",
        icon: Hotel,
      },
    ],
  },
  {
    id: "economy",
    label: "Ekonomija i financije",
    description: "Quisque himenaeos tempor pharetra.",
    icon: Wallet,
    dataSets: [
      {
        label: "Kapitalna ulaganja 2024.",
        description: "Velit cursus magna fringilla natoque.",
        icon: Banknote,
      },
      {
        label: "Kapitalna ulaganja 2023",
        description: "Velit cursus magna fringilla natoque.",
        icon: Banknote,
      },
    ],
  },
  {
    id: "public-sector",
    label: "Javni sektor i ustanove",
    description: "Aenean lobortis gravida finibus torquent accumsan.",
    icon: Landmark,
    dataSets: [
      {
        label: "Područni odsjeci",
        description: "Velit cursus magna fringilla natoque.",
        icon: Landmark,
      },
      {
        label: "Gradska trgovačka društva",
        description: "Velit cursus magna fringilla natoque.",
        icon: Landmark,
      },
      {
        label: "Druge javne ustanove",
        description: "Velit cursus magna fringilla natoque.",
        icon: Landmark,
      },
      {
        label: "Zdravstvene ustanove",
        description: "Velit cursus magna fringilla natoque.",
        icon: Hospital,
      },
      {
        label: "Sjedišta gradskih četvrti",
        description: "Velit cursus magna fringilla natoque.",
        icon: Landmark,
      },
      {
        label: "Mjesna samouprava",
        description: "Velit cursus magna fringilla natoque.",
        icon: Landmark,
      },
      {
        label: "Crkve (Rimokatoličke Župe)",
        description: "Velit cursus magna fringilla natoque.",
        icon: Church,
      },
      {
        label: "Područni uredi",
        description: "Velit cursus magna fringilla natoque.",
        icon: BookMarked,
      },
      {
        label: "Visokoškolske ustanove",
        description: "Velit cursus magna fringilla natoque.",
        icon: GraduationCap,
      },
      {
        label: "Tijela državne uprave",
        description: "Velit cursus magna fringilla natoque.",
        icon: Landmark,
      },
    ],
  },
  {
    id: "environment",
    label: "Okoliš",
    description:
      "Porttitor eleifend montes curabitur aptent risus ullamcorper.",
    icon: TreePine,
    dataSets: [
      {
        label: "Polupodzemni spremnik",
        description: "Velit cursus magna fringilla natoque.",
        icon: Trash2,
      },
      {
        label: "Podzemni spremnik",
        description: "Velit cursus magna fringilla natoque.",
        icon: Trash2,
      },
      {
        label: "Pojilice sa pitkom vodom",
        description: "Velit cursus magna fringilla natoque.",
        icon: Droplet,
      },
      {
        label: "Topografska osnova 2018. Vegetacija i vrste zemljišta",
        description: "Velit cursus magna fringilla natoque.",
        icon: Map,
      },
      {
        label: "Topografska osnova 2018. Vode",
        description: "Velit cursus magna fringilla natoque.",
        icon: Map,
      },
      {
        label: "Gradski vrt",
        description: "Velit cursus magna fringilla natoque.",
        icon: Rose,
      },
      {
        label: "Gradski vrt Point",
        description: "Velit cursus magna fringilla natoque.",
        icon: Rose,
      },
      {
        label: "Reciklažna dvorišta grada Zagreba",
        description: "Velit cursus magna fringilla natoque.",
        icon: Recycle,
      },
      {
        label: "Kvaliteta zraka",
        description: "Velit cursus magna fringilla natoque.",
        icon: Wind,
      },
      {
        label: "Brownfield površine",
        description: "Velit cursus magna fringilla natoque.",
        icon: Blocks,
      },
    ],
  },
  {
    id: "agriculture",
    label: "Poljoprivreda, ribarstvo, šumarstvo i hrana",
    description: "Bibendum tristique congue maximus litora sem vulputate.",
    icon: Sprout,
    dataSets: [
      {
        label: "Granice dopuštenog držanja domaćih životinja",
        description: "Velit cursus magna fringilla natoque.",
        icon: Cat,
      },
      {
        label: "Gradske tržnice",
        description: "Velit cursus magna fringilla natoque.",
        icon: Store,
      },
      {
        label: "Zajednička lovišta",
        description: "Velit cursus magna fringilla natoque.",
        icon: BowArrow,
      },
      {
        label: "Program zaštite divljači",
        description: "Velit cursus magna fringilla natoque.",
        icon: Rabbit,
      },
    ],
  },
  {
    id: "judiciary",
    label: "Pravosuđe, pravni sustav i javna sigurnost",
    description: "Pulvinar maecenas placerat faucibus per senectus ligula.",
    icon: Gavel,
    dataSets: [
      {
        label: "Nadzorne kamere",
        description: "Velit cursus magna fringilla natoque.",
        icon: Cctv,
      },
      {
        label: "Policija",
        description: "Velit cursus magna fringilla natoque.",
        icon: Siren,
      },
      {
        label: "Vatrogasci",
        description: "Velit cursus magna fringilla natoque.",
        icon: FireExtinguisher,
      },
    ],
  },
  {
    id: "traffic",
    label: "Promet",
    description: "Efficitur ridiculus iaculis parturient morbi netus aliquam.",
    icon: Road,
    dataSets: [
      {
        label: "Autobusna stajališta ZET",
        description: "Velit cursus magna fringilla natoque.",
        icon: Bus,
      },
      {
        label: "Željeznička stajališta HŽ",
        description: "Velit cursus magna fringilla natoque.",
        icon: TrainFront,
      },
      {
        label: "Pješačka zona",
        description: "Velit cursus magna fringilla natoque.",
        icon: Footprints,
      },
      {
        label: "Topografska osnova 2018. Promet",
        description: "Velit cursus magna fringilla natoque.",
        icon: Map,
      },
      {
        label: "Zone rezerviranih parkirališnih mjesta",
        description: "Velit cursus magna fringilla natoque.",
        icon: SquareParking,
      },
      {
        label: "Javne garaže",
        description: "Velit cursus magna fringilla natoque.",
        icon: Rows4,
      },
      {
        label: "Javna parkirališta za bicikle",
        description: "Velit cursus magna fringilla natoque.",
        icon: SquareParking,
      },
      {
        label: "Sustav javnih bicikala",
        description: "Velit cursus magna fringilla natoque.",
        icon: Bike,
      },
      {
        label: "Biciklističke staze",
        description: "Velit cursus magna fringilla natoque.",
        icon: Road,
      },
      {
        label: "Nadzorne kamere",
        description: "Velit cursus magna fringilla natoque.",
        icon: Cctv,
      },
      {
        label: "Taxi stajališta",
        description: "Velit cursus magna fringilla natoque.",
        icon: CarTaxiFront,
      },
      {
        label: "Električne punionice",
        description: "Velit cursus magna fringilla natoque.",
        icon: Cable,
      },
      {
        label: "Tramvajska stajališta ZET",
        description: "Velit cursus magna fringilla natoque.",
        icon: TramFront,
      },
      {
        label: "Benzinske postaje",
        description: "Velit cursus magna fringilla natoque.",
        icon: Fuel,
      },
    ],
  },
  {
    id: "society",
    label: "Stanovništvo i društvo",
    description: "Convallis sapien molestie cubilia pretium orci hendrerit.",
    icon: PersonStanding,
    dataSets: [
      {
        label: "Javni zdenci",
        description: "Velit cursus magna fringilla natoque.",
        icon: Droplets,
      },
      {
        label: "Domovi za djecu",
        description: "Velit cursus magna fringilla natoque.",
        icon: HouseHeart,
      },
      {
        label: "Ustanove za osobe s invaliditetom",
        description: "Velit cursus magna fringilla natoque.",
        icon: Accessibility,
      },
      {
        label: "Zborna mjesta civilne zaštite Grada Zagreba",
        description: "Velit cursus magna fringilla natoque.",
        icon: Landmark,
      },
      {
        label: "Evakuacijske površine Grada Zagreba",
        description: "Velit cursus magna fringilla natoque.",
        icon: Map,
      },
      {
        label: "Hrvatski zavod za socijalni rad",
        description: "Velit cursus magna fringilla natoque.",
        icon: Landmark,
      },
      {
        label: "Nadležne institucije socijalne zaštite",
        description: "Velit cursus magna fringilla natoque.",
        icon: Landmark,
      },
      {
        label: "Ostale djelatnosti socijalne skrbi",
        description: "Velit cursus magna fringilla natoque.",
        icon: Landmark,
      },
      {
        label: "Ustanove za branitelje",
        description: "Velit cursus magna fringilla natoque.",
        icon: Shield,
      },
      {
        label: "Ustanove za beskućnike",
        description: "Velit cursus magna fringilla natoque.",
        icon: Landmark,
      },
      {
        label: "Domovi za starije osobe",
        description: "Velit cursus magna fringilla natoque.",
        icon: House,
      },
      {
        label: "Javni WC-i",
        description: "Velit cursus magna fringilla natoque.",
        icon: Toilet,
      },
      {
        label: "Besplatna WiFi mreža",
        description: "Velit cursus magna fringilla natoque.",
        icon: Wifi,
      },
      {
        label: "Dječji vrtići",
        description: "Velit cursus magna fringilla natoque.",
        icon: Balloon,
      },
      {
        label: "Gradski vrt",
        description: "Velit cursus magna fringilla natoque.",
        icon: Rose,
      },
      {
        label: "Sjedišta gradskih četvrti",
        description: "Velit cursus magna fringilla natoque.",
        icon: Landmark,
      },
      {
        label: "Gradske tržnice",
        description: "Velit cursus magna fringilla natoque.",
        icon: Store,
      },
      {
        label: "Gradski vrt Point",
        description: "Velit cursus magna fringilla natoque.",
        icon: Rose,
      },
      {
        label: "Kapitalna ulaganja 2023",
        description: "Velit cursus magna fringilla natoque.",
        icon: Banknote,
      },
      {
        label: "Javne površine za pse",
        description: "Velit cursus magna fringilla natoque.",
        icon: Dog,
      },
      {
        label: "Javna sportska igrališta",
        description: "Velit cursus magna fringilla natoque.",
        icon: Volleyball,
      },
      {
        label: "Nadležna institucija",
        description: "Velit cursus magna fringilla natoque.",
        icon: Landmark,
      },
      {
        label: "Vjerske zajednice",
        description: "Velit cursus magna fringilla natoque.",
        icon: Church,
      },
      {
        label: "Vatrogasci",
        description: "Velit cursus magna fringilla natoque.",
        icon: FireExtinguisher,
      },
    ],
  },
  {
    id: "health-care",
    label: "Zdravstvo",
    description: "Nascetur vehicula platea condimentum rutrum eros donec.",
    icon: HeartPulse,
    dataSets: [
      {
        label: "Zdravstvene ustanove",
        description: "Velit cursus magna fringilla natoque.",
        icon: Cross,
      },
      {
        label: "Domovi zdravlja",
        description: "Velit cursus magna fringilla natoque.",
        icon: Cross,
      },
      {
        label: "Ljekarne",
        description: "Velit cursus magna fringilla natoque.",
        icon: Cross,
      },
    ],
  },
  {
    id: "science",
    label: "Znanost i tehnologija",
    description: "Sollicitudin feugiat penatibus tincidunt mauris.",
    icon: Microscope,
    dataSets: [
      {
        label: "Telekomunikacijski razvodni ormarići",
        description: "Velit cursus magna fringilla natoque.",
        icon: Zap,
      },
    ],
  },
];
